#!/usr/bin/env php
<?php

$loaded = false;

$files = [
    __DIR__.'/../../autoload.php',
    __DIR__.'/vendor/autoload.php',
    getcwd().'vendor/autoload.php',
];
foreach ($files as $file) {
    if (file_exists($file)) {
        require_once $file;
        $loaded = true;
        break;
    }
}

if (!$loaded) {
    die(
        'You need to set up the project dependencies using the following commands:'.PHP_EOL.
        'wget http://getcomposer.org/composer.phar'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
}


$application = new Oneshoe\CloverToBitbucket\Console\Application();
$application->run();
